### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by liuxian77** [esimov/triangle-app#2]
I downloaded direactly the exe. file but appares the server error.
Is this App still running? 
Also the button to generate/ cancel only can appare half in the interface.
Very curious about it. I think its effect is very dynamic and artistic so really want to try it. 
Thank you in anticipate!

**Comment by esimov** [comment]
As I mentioned in the readme you need to have Go installed on your machine, since the app is communicating with a Go backend where all the aesthetic transformation is happening. This error means that the Go server has not been started. Please follow the readme doc and it should work.
